### PR TITLE
increase the volume of several music tracks

### PR DESCRIPTION
**Pull request by exelotl**

### CODE REVIEW

**Comment by GValiente** [comment]
All shared jingles are played with volume 0.5.
Why do you want to increase the volume of the transition jingles to the double of that?
I think their volume is fine right now.

**Comment by exelotl** [comment]
Are you sure? At volume 0.5 the transitions are definitely too quiet compared to the microgame music. After this change all music sounds similar in volume to me (except for a few outliers like Os Magnum which is too loud, candle game too quiet).

Even after the boost, all music is slightly quieter than the GBA BIOS startup sound (but I think that's ok).

**Comment by GValiente** [comment]
I trust your hearing more than mine :)

**Comment by copyrat90** [comment]
> After this change all music sounds similar in volume to me (except for a few outliers like Os Magnum which is too loud, candle game too quiet).

I found out why my Candle game is too quiet.
It's the only game that uses DMG music, and VGM Player integrated in Butano never sets the DMG Master volume, which defaults to `25%`.

I already created an issue regarding this in Butano.
https://github.com/GValiente/butano/issues/56

**Pull request merged**
